[project]
name = "midi-to-chataigne"
version = "0.1.0"
description = "Convert MIDI files to Chataigne sequences"
dependencies = [
    "mido>=1.3.2",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

